-- ═══════════════════════════════════════════════════════════════════════════
-- MIGRACIÓN 003: Normalización de IDs de proveedor
-- Objetivo: proveedor_importacion.id 1 → 654 (ID nativo del sistema PHP)
--           + proveedor_id en tabla color
-- Ejecutada: 2026-04-21 ✅
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

-- ── PASO 1: Soltar FKs que apuntan a proveedor_importacion.id ──────────────
ALTER TABLE linea              DROP CONSTRAINT linea_proveedor_id_fkey;
ALTER TABLE material           DROP CONSTRAINT material_proveedor_id_fkey;
ALTER TABLE compra_legal       DROP CONSTRAINT compra_legal_proveedor_importacion_id_fkey;
ALTER TABLE intencion_compra   DROP CONSTRAINT intencion_compra_id_proveedor_fkey;
ALTER TABLE pedido_proveedor   DROP CONSTRAINT pedido_proveedor_proveedor_importacion_id_fkey;
ALTER TABLE ric                DROP CONSTRAINT ric_proveedor_id_fkey;

-- ── PASO 2: Convertir a GENERATED BY DEFAULT para poder editar el PK ───────
ALTER TABLE proveedor_importacion
    ALTER COLUMN id SET GENERATED BY DEFAULT;

-- ── PASO 3: Cambiar el PK de 1 → 654 ──────────────────────────────────────
UPDATE proveedor_importacion SET id = 654 WHERE id = 1;

-- ── PASO 4: Volver a GENERATED ALWAYS
ALTER TABLE proveedor_importacion
    ALTER COLUMN id SET GENERATED ALWAYS;

-- ── PASO 5: Actualizar todas las tablas hijas ──────────────────────────────
UPDATE linea            SET proveedor_id             = 654 WHERE proveedor_id             = 1;
UPDATE material         SET proveedor_id             = 654 WHERE proveedor_id             = 1;
UPDATE compra_legal     SET proveedor_importacion_id = 654 WHERE proveedor_importacion_id = 1;
UPDATE intencion_compra SET id_proveedor             = 654 WHERE id_proveedor             = 1;
UPDATE pedido_proveedor SET proveedor_importacion_id = 654 WHERE proveedor_importacion_id = 1;
UPDATE ric              SET proveedor_id             = 654 WHERE proveedor_id             = 1;

-- ── PASO 6: Re-crear FKs ───────────────────────────────────────────────────
ALTER TABLE linea            ADD CONSTRAINT linea_proveedor_id_fkey
    FOREIGN KEY (proveedor_id) REFERENCES proveedor_importacion(id);
ALTER TABLE material         ADD CONSTRAINT material_proveedor_id_fkey
    FOREIGN KEY (proveedor_id) REFERENCES proveedor_importacion(id);
ALTER TABLE compra_legal     ADD CONSTRAINT compra_legal_proveedor_importacion_id_fkey
    FOREIGN KEY (proveedor_importacion_id) REFERENCES proveedor_importacion(id);
ALTER TABLE intencion_compra ADD CONSTRAINT intencion_compra_id_proveedor_fkey
    FOREIGN KEY (id_proveedor) REFERENCES proveedor_importacion(id);
ALTER TABLE pedido_proveedor ADD CONSTRAINT pedido_proveedor_proveedor_importacion_id_fkey
    FOREIGN KEY (proveedor_importacion_id) REFERENCES proveedor_importacion(id);
ALTER TABLE ric              ADD CONSTRAINT ric_proveedor_id_fkey
    FOREIGN KEY (proveedor_id) REFERENCES proveedor_importacion(id);

-- ── PASO 7: Ajustar secuencia — próximo proveedor empieza en 655 ───────────
SELECT setval('public.proveedor_importacion_id_seq', 654, true);

-- ── PASO 8: Agregar proveedor_id a tabla color ────────────────────────────
ALTER TABLE color ADD COLUMN proveedor_id bigint;
UPDATE color SET proveedor_id = 654;
ALTER TABLE color ALTER COLUMN proveedor_id SET NOT NULL;
ALTER TABLE color ADD CONSTRAINT color_proveedor_id_fkey
    FOREIGN KEY (proveedor_id) REFERENCES proveedor_importacion(id);

COMMIT;
