-- =============================================================================
-- 030 · Staging multi-tienda + importadora (Excel → Supabase)
-- Propósito: ingestar filas Stock/Venta por Tienda_1..3 e Importadora hasta
--            absorber todo en tablas operativas. El módulo Nexus lee/escribe aquí.
-- Idempotente: CREATE IF NOT EXISTS + comentarios.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.retail_multitienda_staging (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id            uuid NOT NULL DEFAULT gen_random_uuid(),
    batch_label         text NULL,
    origen_tienda       text NOT NULL,
    tipo_movimiento     text NOT NULL,
    fecha_mov           date NOT NULL,
    linea_code          text NOT NULL,
    referencia_code     text NOT NULL,
    material_id         bigint NOT NULL,
    color_id            bigint NOT NULL,
    grada               text NOT NULL,
    cantidad            numeric NOT NULL DEFAULT 0,
    precio_unitario     numeric NULL,
    monto               numeric NULL,
    archivo_origen      text NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    created_by          text NULL,
    -- Clave artículo (5 pilares agregados sin talla en la clave; grada queda en fila)
    sku_key             text GENERATED ALWAYS AS (
        trim(both ' ' from linea_code) || '|' || trim(both ' ' from referencia_code)
        || '|' || material_id::text || '|' || color_id::text
    ) STORED
);

COMMENT ON TABLE public.retail_multitienda_staging IS
  'Staging Excel multi-tienda: Stock/Venta por sucursal + Stock importadora. Origen híbrido hasta ETL definitivo.';

COMMENT ON COLUMN public.retail_multitienda_staging.origen_tienda IS
  'Ej: Tienda_1, Tienda_2, Tienda_3, Importadora';
COMMENT ON COLUMN public.retail_multitienda_staging.tipo_movimiento IS
  'Stock o Venta (texto libre; normalizar en app a mayúsculas si se desea)';
COMMENT ON COLUMN public.retail_multitienda_staging.grada IS
  'Talla simple (34) o grada compuesta 34(1 2 3 3 2 1) según Excel fuente';

CREATE INDEX IF NOT EXISTS idx_retail_staging_batch
    ON public.retail_multitienda_staging (batch_id);
CREATE INDEX IF NOT EXISTS idx_retail_staging_sku
    ON public.retail_multitienda_staging (sku_key);
CREATE INDEX IF NOT EXISTS idx_retail_staging_linea_ref
    ON public.retail_multitienda_staging (linea_code, referencia_code);
CREATE INDEX IF NOT EXISTS idx_retail_staging_origen_tipo
    ON public.retail_multitienda_staging (origen_tienda, tipo_movimiento);
CREATE INDEX IF NOT EXISTS idx_retail_staging_fecha
    ON public.retail_multitienda_staging (fecha_mov DESC);
