-- =============================================================================
-- 060 · Retail — Excel VTA SM, hoja «st+vt+RC»
--
-- Sales Report → registro_ventas_general_v2 (otro Excel).
-- Retail       → esta tabla (hoja st+vt+RC).
-- Pilares: FKs opcionales para filtros e imágenes.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.registro_st_vt_rc_reposicion (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id                    uuid NOT NULL DEFAULT gen_random_uuid(),
    batch_label                 text NULL,
    fecha_mov                   date NULL,
    origen_holding              text NOT NULL DEFAULT '',
    tipo_movimiento             text NOT NULL DEFAULT '',
    codigo_barras               text NULL,
    linea_codigo_proveedor      text NOT NULL,
    referencia_codigo_proveedor text NOT NULL,
    excel_material_code         text NULL,
    excel_color_code            text NULL,
    linea_id                    bigint NULL,
    referencia_id               bigint NULL,
    material_id                 bigint NULL,
    color_id                    bigint NULL,
    grada                       text NOT NULL DEFAULT '(sin grada)',
    cantidad                    numeric NOT NULL DEFAULT 0,
    precio_unitario             numeric NULL,
    monto                       numeric NULL,
    imagen_nombre               text NULL,
    archivo_origen              text NULL,
    excel_sheet                 text NOT NULL DEFAULT 'st+vt+RC',
    created_at                  timestamptz NOT NULL DEFAULT now(),
    created_by                  text NULL,
    sku_key                     text GENERATED ALWAYS AS (
        trim(both ' ' from linea_codigo_proveedor) || '|'
        || trim(both ' ' from referencia_codigo_proveedor) || '|'
        || COALESCE(trim(both ' ' from excel_material_code), '') || '|'
        || COALESCE(trim(both ' ' from excel_color_code), '')
    ) STORED
);

COMMENT ON TABLE public.registro_st_vt_rc_reposicion IS
  'Retail: Excel VTA SM, hoja st+vt+RC. Independiente de registro_ventas_general_v2 (Sales Report).';

COMMENT ON COLUMN public.registro_st_vt_rc_reposicion.origen_holding IS
  'Nodo del holding (ej. tienda, depósito). Columna Tienda del Excel.';
COMMENT ON COLUMN public.registro_st_vt_rc_reposicion.tipo_movimiento IS
  'ST / VT / RC u otro según columna tipo del Excel.';
COMMENT ON COLUMN public.registro_st_vt_rc_reposicion.excel_sheet IS
  'Siempre la hoja operativa st+vt+RC; otras hojas del libro no se importan.';

CREATE INDEX IF NOT EXISTS idx_reposicion_batch
    ON public.registro_st_vt_rc_reposicion (batch_id);
CREATE INDEX IF NOT EXISTS idx_reposicion_fecha
    ON public.registro_st_vt_rc_reposicion (fecha_mov DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_reposicion_sku
    ON public.registro_st_vt_rc_reposicion (sku_key);
CREATE INDEX IF NOT EXISTS idx_reposicion_origen_tipo
    ON public.registro_st_vt_rc_reposicion (origen_holding, tipo_movimiento);
CREATE INDEX IF NOT EXISTS idx_reposicion_linea_ref
    ON public.registro_st_vt_rc_reposicion (linea_codigo_proveedor, referencia_codigo_proveedor);
